# Generated by Django 3.0.7 on 2021-03-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('designacion', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/%Y/%m/%d/')),
                ('facebook_link', models.URLField(max_length=100)),
                ('twiter_link', models.URLField(max_length=100)),
                ('google_plus', models.URLField(max_length=100)),
                ('fec_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
