# Generated by Django 3.0.7 on 2021-03-25 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_auto_20210324_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carro',
            name='fec_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 23, 29, 53, 953556)),
        ),
        migrations.AlterField(
            model_name='carro',
            name='puertas',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
        migrations.AlterField(
            model_name='carro',
            name='tipo_combustible',
            field=models.CharField(max_length=50),
        ),
    ]
