# Generated by Django 3.0.7 on 2021-05-03 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_auto_20210325_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='fec_creacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 5, 3, 12, 45, 40, 124211)),
        ),
    ]
